// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbvRAiynjKPFjkpnvIhFcNoK3vHuqfPAw',
    appId: '1:778528078870:web:3f090e50870db319c28937',
    messagingSenderId: '778528078870',
    projectId: 'appmusic-b8273',
    authDomain: 'appmusic-b8273.firebaseapp.com',
    storageBucket: 'appmusic-b8273.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm_PIA6V3I6Gt2-bYmCG9ElowGyi7xneE',
    appId: '1:778528078870:android:b81a4894b2af5f7ac28937',
    messagingSenderId: '778528078870',
    projectId: 'appmusic-b8273',
    storageBucket: 'appmusic-b8273.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLlx7n6AePafeuruOxGAd-PK8mY9oFVFA',
    appId: '1:778528078870:ios:9e4afb33d304b362c28937',
    messagingSenderId: '778528078870',
    projectId: 'appmusic-b8273',
    storageBucket: 'appmusic-b8273.firebasestorage.app',
    iosBundleId: 'com.example.appMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLlx7n6AePafeuruOxGAd-PK8mY9oFVFA',
    appId: '1:778528078870:ios:8be3804085cc6182c28937',
    messagingSenderId: '778528078870',
    projectId: 'appmusic-b8273',
    storageBucket: 'appmusic-b8273.firebasestorage.app',
    iosBundleId: 'com.Appmusic.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbvRAiynjKPFjkpnvIhFcNoK3vHuqfPAw',
    appId: '1:778528078870:web:67b1b9bd1f25330dc28937',
    messagingSenderId: '778528078870',
    projectId: 'appmusic-b8273',
    authDomain: 'appmusic-b8273.firebaseapp.com',
    storageBucket: 'appmusic-b8273.firebasestorage.app',
  );
}